name: Docker Image CI

on:
  workflow_dispatch:

permissions:
  contents: read
  packages: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata from package.json
        run: |
          echo "NAME=$(cat package.json | jq -r '.name')" >> "$GITHUB_OUTPUT"
          echo "VERSION=$(cat package.json | jq -r '.version')" >> "$GITHUB_OUTPUT"
        id: metadata

      - name: Build and push Docker Image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ghcr.io/fidlabs/${{ steps.metadata.outputs.NAME }}:${{ steps.metadata.outputs.VERSION }}

      - name: Extract metadata from FE package.json
        working-directory: frontend
        run: |
          echo "NAME=$(cat package.json | jq -r '.name')" >> "$GITHUB_OUTPUT"
          echo "VERSION=$(cat package.json | jq -r '.version')" >> "$GITHUB_OUTPUT"
        id: fe-metadata

      - name: Build and push Docker Image
        uses: docker/build-push-action@v5
        with:
          context: ./frontend
          push: true
          tags: ghcr.io/fidlabs/${{ steps.fe-metadata.outputs.NAME }}:${{ steps.fe-metadata.outputs.VERSION }}
